name: The Break of Don
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1655301284044981
title: 'The Break of Don - Adventures in Parenting, Marriage, and Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7184877516701818
  lightness: 0.1559562492184341
  saturation: 0.8828575499355793
  rhythmicContrast: 0.75
purpose: []
