analytics: {}
color:
  brandColors:
    - '#7db7e9'
    - '#1c1f28'
    - '#f3f4f8'
    - '#a28172'
    - '#bc3521'
  brandStrength: 0.5
  lightness: 0.1875
  rhythmicContrast: 0.750845
  saturation: 0.673142
cta: {}
layout_spectrum: 1
name: The Break of Don
opengraph: {}
purpose: []
typography_spectrum: 0.36256
