analytics: {}
color:
  brandColors:
    - '#A88888'
    - '#5B2D29'
    - '#606878'
    - '#B05850'
    - '#F0D078'
  brandStrength: 1
  lightness: 0.155956
  rhythmicContrast: 0.419764
  saturation: 0.882857
cta: {}
layout_spectrum: 0.902872
name: The Break of Don
opengraph: {}
purpose: []
typography_spectrum: 0.112331
