analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.718487
  lightness: 0.155956
  rhythmicContrast: 0.75
  saturation: 0.882857
cta: {}
layout_spectrum: 1
name: The Break of Don
opengraph: {}
purpose: []
typography_spectrum: 0.112331
